; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5

; RUN: opt -O3 -S < %s | FileCheck %s

define i64 @slice_iter_roundtrip_via_slice(ptr %p, i64 %x) {
; CHECK-LABEL: define i64 @slice_iter_roundtrip_via_slice(
; CHECK-SAME: ptr [[P:%.*]], i64 [[X:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[START:.*:]]
; CHECK-NEXT:    [[PTR:%.*]] = ptrtoint ptr [[P]] to i64
; CHECK-NEXT:    [[DIFF:%.*]] = sub i64 [[X]], [[PTR]]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 [[DIFF]]
; CHECK-NEXT:    [[LEN:%.*]] = ptrtoint ptr [[GEP]] to i64
; CHECK-NEXT:    ret i64 [[LEN]]
;
start:
  %ptr = ptrtoint ptr %p to i64
  %diff = sub i64 %x, %ptr
  %gep = getelementptr inbounds i8, ptr %p, i64 %diff
  %len = ptrtoint ptr %gep to i64
  ret i64 %len
}
